#! /usr/bin/env python
# encoding: utf-8

extra_linkflags = []
CXX = bld.env.get_flat("CXX")
# Matches MSVC
if 'CL.exe' in CXX or 'cl.exe' in CXX:
    extra_linkflags = ['/EXPORT:initkodo']

bld(
    features='cxx cxxshlib pyext',
    source=bld.path.ant_glob('**/*.cpp'),
    target='kodo',
    linkflags=extra_linkflags,
    use=[
        'boost_filesystem',
        'boost_includes',
        'boost_python',
        'boost_system',
        'fifi_includes',
        'kodo_includes',
        'sak_includes',
    ]
)
